"""Added time_limit and time_unit to Quiz model

Revision ID: 9eda72ae4703
Revises: 4e15bbfa9667
Create Date: 2025-04-13 20:15:35.945253

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9eda72ae4703'
down_revision = '4e15bbfa9667'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('live_quiz_answers')
    op.drop_table('live_quiz_participants')
    op.drop_table('live_quiz_rooms')
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('time_unit', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_column('time_unit')
        batch_op.drop_column('time_limit')

    op.create_table('live_quiz_participants',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('live_quiz_participants_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('display_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('joined_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('current_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['live_quiz_rooms.id'], name='live_quiz_participants_room_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='live_quiz_participants_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='live_quiz_participants_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('live_quiz_rooms',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('live_quiz_rooms_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('room_code', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('quiz_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('host_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('question_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_question_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], name='live_quiz_rooms_host_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name='live_quiz_rooms_quiz_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='live_quiz_rooms_pkey'),
    sa.UniqueConstraint('room_code', name='live_quiz_rooms_room_code_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('live_quiz_answers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('participant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('option_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('answered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('time_taken', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('points_earned', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['option_id'], ['options.id'], name='live_quiz_answers_option_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['live_quiz_participants.id'], name='live_quiz_answers_participant_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name='live_quiz_answers_question_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='live_quiz_answers_pkey')
    )
    # ### end Alembic commands ###
